version: 2

defaults: &defaults
  working_directory: /workspace
  docker:
    - image: docker:18.06.1-ce

jobs:
  build:
    <<: *defaults
    steps:
      - run:
          name: "Install tools"
          command: |
            sed -i -e 's/v[[:digit:]]\.[[:digit:]]/edge/g' /etc/apk/repositories
            apk add --update --update-cache curl git bash protobuf-dev util-linux
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "Set Docker image name"
          command: |
            echo "export TAG=0.1.${CIRCLE_BUILD_NUM:-0}" >> "$BASH_ENV"
            echo "export IMAGE=proto-registry-builder:${CIRCLE_BUILD_NUM:-0}" >> "$BASH_ENV"
      - run:
          name: "Build"
          command: exec /bin/bash -c '.circleci/build "$IMAGE"'
      - run:
          name: "Test"
          command: exec /bin/bash -c '.circleci/test "$IMAGE"'
      - run:
          name: "Save image"
          command: exec /bin/bash -c 'docker save "$IMAGE" | gzip > image.tar.gz && cp "$BASH_ENV" bashenv'
      - persist_to_workspace:
          root: /workspace
          paths:
            - image.tar.gz
            - bashenv
  deploy:
    <<: *defaults
    steps:
      - run:
          name: "Install tools"
          command: "apk add --update curl bash"
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: /workspace
      - run:
          name: "Load image"
          command: "< image.tar.gz gunzip | docker load && cp bashenv $BASH_ENV"
      - run:
          name: "Deploy"
          command: exec /bin/bash -c '.circleci/deploy "$IMAGE"'

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          context: proto-gcr-push-access
          filters:
            branches:
              only:
                - master
